version: '3'
services:
  your-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "4000:4000"
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_dev
    volumes:
       - db-data:/var/lib/postgresql/data

volumes:
  db-data:
